import numpy as np
from bisect import bisect_right as BSR, bisect_left as BSL
from itertools import combinations as itrtls_combinations
import datetime
from typing import Dict, List, Tuple, Any, Union, Generator, Set, Optional, Iterator, Callable
from numpy.typing import NDArray

# Import custom type definitions
from krysztalki.core.crystal_types import (
    SymOpDict, SymmetryBaseDict, SymmetryOperation, SymmetryMatrix,
    Point3D, PointArray, PointArrayTransposed, AnalysisResult
)


def generateSymetryBase() -> SymmetryBaseDict:
    """
    Generate all possible transformation matrices in crystallographic cell.

    Currently hexagonal axis and trigonal axis in dir [001] are not implemented.

    Returns:
        Dictionary with symmetry operations organized by type and direction
    """
    s3d2 = np.sqrt(3) / 2
    return {
        "c": {"000": np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])},
        "m": {
            "100": np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]]),
            "010": np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]]),
            "001": np.array([[1, 0, 0], [0, 1, 0], [0, 0, -1]]),
            "110": np.array([[0, -1, 0], [-1, 0, 0], [0, 0, 1]]),
            "011": np.array([[1, 0, 0], [0, 0, -1], [0, -1, 0]]),
            "101": np.array([[0, 0, -1], [0, 1, 0], [-1, 0, 0]]),
            "-101": np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]]),
            "-110": np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]]),
            "0-11": np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]]),
        },
        "2": {
            "100": np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]]),
            "010": np.array([[-1, 0, 0], [0, 1, 0], [0, 0, -1]]),
            "001": np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]]),
            "110": np.array([[0, 1, 0], [1, 0, 0], [0, 0, -1]]),
            "101": np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]]),
            "011": np.array([[-1, 0, 0], [0, 0, 1], [0, 1, 0]]),
            "-110": np.array([[0, -1, 0], [-1, 0, 0], [0, 0, -1]]),
            "-101": np.array([[0, 0, -1], [0, -1, 0], [-1, 0, 0]]),
            "0-11": np.array([[-1, 0, 0], [0, 0, -1], [0, -1, 0]]),
        },
        "3": {
            #             "001":np.array([[-0.5,-s3d2,0],[s3d2,-0.5,0],[0,0,1]]),
            "111": np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]]),
            "-111": np.array([[0, -1, 0], [0, 0, 1], [-1, 0, 0]]),
            "1-11": np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]]),
            "11-1": np.array([[0, 1, 0], [0, 0, -1], [-1, 0, 0]]),
        },
        "-3": {
            #             "001":np.array([[0.5,s3d2,0],[-s3d2,0.5,0],[0,0,-1]]),
            "111": np.array([[0, 0, -1], [-1, 0, 0], [0, -1, 0]]),
            "-111": np.array([[0, 1, 0], [0, 0, -1], [1, 0, 0]]),
            "1-11": np.array([[0, 1, 0], [0, 0, 1], [-1, 0, 0]]),
            "11-1": np.array([[0, -1, 0], [0, 0, 1], [1, 0, 0]]),
        },
        "4": {
            "100": np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]]),
            "010": np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]]),
            "001": np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]]),
        },
        "-4": {
            "100": np.array([[-1, 0, 0], [0, 0, 1], [0, -1, 0]]),
            "010": np.array([[0, 0, -1], [0, -1, 0], [1, 0, 0]]),
            "001": np.array([[0, 1, 0], [-1, 0, 0], [0, 0, -1]]),
        },  # ,
        #         "6":{
        #             "001":np.array([[0.5,-s3d2,0],[s3d2,0.5,0],[0,0,1]])
        #         },
        #         "-6":{
        #             "001":np.array([[-0.5,s3d2,0],[-s3d2,-0.5,0],[0,0,-1]])
        #         }
    }


# def listadous(macierz, punktprzes):
#     punkt = np.matmul(macierz,punktprzes)  # np.matmul
#     punkt = np.around(punkt,6)
#     while not np.allclose(punkt, punktprzes):   # porownajPunkty
#         yield punkt
#         punkt = np.matmul(macierz,punkt)
#         punkt = np.around(punkt,6)


def listadous(macierz: SymmetryMatrix, punktprzes: Point3D) -> Generator[Point3D, None, None]:
    """
    Generate all points produced by repeated application of a transformation matrix.

    Args:
        macierz: Transformation matrix to apply
        punktprzes: Starting point

    Yields:
        Points generated by repeated transformation until returning to the original point
    """
    punkt = np.matmul(macierz, punktprzes)
    while not porownajPunkty(punkt, punktprzes):
        yield punkt
        punkt = np.matmul(macierz, punkt)


def makelist() -> List[SymmetryOperation]:
    """
    List all names of symmetry operations.

    Returns:
        List of tuples (symmetry_type, direction) for all available symmetries
    """
    Matrixes = generateSymetryBase()
    mylist = []
    for Mainkey in Matrixes.keys():
        for Subkey in Matrixes[Mainkey].keys():
            mylist.append((Mainkey, Subkey))
    return mylist[::-1]


def porownajPunkty(p1: Point3D, p2: Point3D) -> bool:
    """
    Compare two points for equality.

    Faster than numpy.all for small arrays.

    Args:
        p1: First point
        p2: Second point

    Returns:
        True if points are equal, False otherwise
    """
    for a, b in zip(p1, p2):
        if a != b:
            return False
    return True


def findindex(searched: Point3D, points: PointArrayTransposed) -> int:
    """
    Binary search for points in a cell.

    Args:
        searched: Point to find
        points: Array of points to search in

    Returns:
        Index of found point or -1 if not found
    """
    indexL, indexR = 0, len(points[0])
    for xyz in range(len(points)):
        numR = BSR(points[xyz][indexL:indexR], searched[xyz])
        numL = BSL(points[xyz][indexL:indexR], searched[xyz])
        if numL < numR:
            indexR = indexL + numR
            indexL += numL
        elif numL == numR:
            indexL += numL
            if indexL != len(points[0]):
                return indexL
            return -1
        else:
            return -1
    return indexL


def findPoints(listofps: Iterator[Point3D], allpoints: PointArrayTransposed, Anti: bool = False) -> bool:
    """
    Check if points are in the list.

    Args:
        listofps: Iterator of points to check
        allpoints: Transposed array of all points
        Anti: When False, looks for vacancies; when True, looks for atoms

    Returns:
        True if all points satisfy the condition, False otherwise
    """
    for ps in listofps:
        indx = findindex(ps, allpoints)
        if (indx + 1 and porownajPunkty(allpoints[:, indx], ps)) == Anti:
            return False
    return True


def findAntiSym_InnerLoop(Matrix: SymmetryMatrix, allpoints: PointArray, vacancies: PointArray) -> bool:
    """
    Check if any of the vacancies transform into valid points.

    Args:
        Matrix: Transformation matrix
        allpoints: Array of all points
        vacancies: Array of vacancy positions

    Returns:
        True if all transformed vacancies satisfy the condition, False otherwise
    """
    for vac in vacancies:
        if not findPoints(listadous(Matrix, vac), allpoints.T, Anti=True):
            return False
    return True


def findAntiSym(matrixes: SymmetryBaseDict, allpoints: PointArray, vacancies: PointArray) -> List[SymmetryOperation]:
    """
    Find symmetries that cannot exist for vacancies in the cell.

    Args:
        matrixes: Dictionary of symmetry matrices
        allpoints: Array of all points
        vacancies: Array of vacancy positions

    Returns:
        List of possible symmetry operations
    """
    allsymmerties = makelist()
    if vacancies.shape == (3,):
        vacancies = np.array([vacancies])
    possymmerties = []
    for el0, el1 in allsymmerties:
        if findAntiSym_InnerLoop(matrixes[el0][el1], allpoints, vacancies):
            possymmerties.append((el0, el1))
    return possymmerties


def findSym_innerLoop(Matrix: SymmetryMatrix, allpoints: PointArray) -> bool:
    """
    Check if all points in the cell satisfy the symmetry.

    Args:
        Matrix: Transformation matrix
        allpoints: Array of all points

    Returns:
        True if all points satisfy the symmetry, False otherwise
    """
    for point in allpoints:
        if not findPoints(listadous(Matrix, point), allpoints.T):
            return False
    return True


def findSym(matrixes: SymmetryBaseDict, allpoints: PointArray, vacancies: PointArray) -> List[SymmetryOperation]:
    """
    Find symmetries that exist in the cell.

    Args:
        matrixes: Dictionary of symmetry matrices
        allpoints: Array of all points
        vacancies: Array of vacancy positions

    Returns:
        List of valid symmetry operations
    """
    symmerties = []
    possym = findAntiSym(matrixes, allpoints, vacancies)
    for el0, el1 in possym:
        if findSym_innerLoop(matrixes[el0][el1], allpoints):
            symmerties.append((el0, el1))
    return symmerties


def makeCellWithVacancies(cell: PointArray, indexes: Union[List[int], Tuple[int, ...], Set[int]]) -> Tuple[PointArray, PointArray]:
    """
    Create two separate arrays: one with vacancies removed and one with just the vacancies.

    Args:
        cell: Array of all points
        indexes: Indices of points to be treated as vacancies (as list, tuple, or set)

    Returns:
        Tuple of (cell with vacancies removed, array of vacancy positions)
    """
    index_set = set(indexes)
    cellVac = []
    Vac = []
    for nr, p in enumerate(cell):
        if nr not in index_set:
            cellVac.append(p)
        else:
            Vac.append(p)
    return np.array(cellVac), np.array(Vac)


def checkAllCells(scell: PointArray, base: str, sumVac: int) -> List[List[SymmetryOperation]]:
    """
    Find all possible vacancy configurations and their symmetries.

    Args:
        scell: Supercell array of points
        base: Base type ("m" for Miller or "w" for Weber)
        sumVac: Number of vacancies to introduce

    Returns:
        List of symmetry operations for each valid vacancy configuration
    """
    Matrixes = generateSymetryBase()
    mylist = []
    for indexes in itrtls_combinations(range(len(scell)), sumVac):
        scellvac, vacancies = makeCellWithVacancies(scell, indexes)
        SYM = findSym(Matrixes, scellvac, vacancies)
        if SYM != []:
            mylist.append(SYM)
    return mylist


def saveOutput(OUTPUT: List[Tuple[Any, List[SymmetryOperation]]], filename: str = "", count: int = 0) -> None:
    """
    Write results to a CSV file with all symmetries for all possible vacancy configurations.

    Args:
        OUTPUT: List of output data to save
        filename: Path to output file (default: auto-generated based on datetime)
        count: Count of empty structures
    """
    newFilename = ""
    if(filename == ""):
        newFilename = f'outputs/output_{datetime.datetime.now().strftime("%y_%m_%d_%H_%M_%S")}.csv'
    else:
        newFilename = filename

    with open(newFilename, "w") as f:
        # f.write(f"amount of empty structures;{count}\n")
        f.write("vacancies indexes;symmetries\n")
        for record in sorted(OUTPUT, key=lambda x: len(x[1]), reverse=True):
            f.write(";".join(str(el) for el in record) + "\n")

    print("Saved")


def analyze_symmetry(crystal: Any, vacancy_count: int = 1) -> AnalysisResult:
    """
    Analyze the symmetry operations of a crystal with vacancies.

    Args:
        crystal: Crystal object to analyze
        vacancy_count: Number of vacancies to introduce

    Returns:
        Dict containing symmetry analysis results

    Example:
        >>> from krysztalki.io.cif import read_cif
        >>> crystal = read_cif("path/to/file.cif")
        >>> results = analyze_symmetry(crystal)
    """
    # Extract the supercell and base type
    # TODO: change to import from newer files. Current files are from old project.
    # TODO: from krysztalki.workDir.Matrix.matrices_new import labels
    # TODO: from krysztalki.workDir.cifParsing import MyCell
    # TODO: from krysztalki.workDir.MMfunc import full_transform, reduce_cell
    # TODO: from krysztalki.SYMfunc import saveOutput

    from krysztalki.io.cif import getSCell

    # Pass a lambda that ignores the filename argument since we already have the crystal
    supercell, base_type = getSCell(lambda _: crystal, "", 1)  # Use empty string instead of None

    # Find all possible symmetry operations for the given vacancy count
    all_symmetries = checkAllCells(supercell, base_type, vacancy_count)

    # Count different symmetry types
    symmetry_counts: Dict[str, int] = {}
    for sym_list in all_symmetries:
        for sym_type, direction in sym_list:
            if sym_type not in symmetry_counts:
                symmetry_counts[sym_type] = 0
            symmetry_counts[sym_type] += 1

    # Prepare the results
    results = {
        "crystal_name": getattr(crystal, "name", "Unknown"),
        "supercell_size": len(supercell),
        "vacancy_count": vacancy_count,
        "base_type": base_type,
        "symmetry_operations_count": len(all_symmetries),
        "symmetry_types": symmetry_counts,
        "detailed_symmetries": all_symmetries
    }

    return results
